filter:
  excluded_paths: [tests/*]

build:
  nodes:
    analysis:
      image: default-bionic
      services:
        mysql: 5.7
      environment:
        php:
          version: 8.1
          ini:
            "xdebug.mode": coverage,
            memory_limit: "-1"
      tests:
        override:
          - command: mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE IF NOT EXISTS lara_geo'
          - command: vendor/bin/phpunit --coverage-clover=coverage-file
            coverage:
              file: coverage-file
              format: php-clover
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
